from selenium.webdriver.common.by import By


class LoginLocators:
    email_id = (By.CSS_SELECTOR, '#loginform-username')
    password_id = (By.CSS_SELECTOR, '#loginform-password')
    captcha_id = (By.XPATH, '//*[@id="recaptcha-anchor"]')
    button_submit = (By.CSS_SELECTOR, '[name="login-button"]')


class StatsLocators:
    statistic_button = (By.CSS_SELECTOR, '#main-menu > li:nth-child(2)')
    main_statistic = (By.CSS_SELECTOR, '#main-menu > li:nth-child(2) > ul > li:nth-child(1) > a > span')
    sub_statistic = (By.CSS_SELECTOR, '#w18 > li:nth-child(2)')


class AdmSideBarLocators:
    work_table_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(1)')
    statistic_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(2)')
    statistic_main_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(2) > ul > li:nth-child(1)')
    statistic_subscribe_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(2) > ul > li:nth-child(2)')
    statistic_transaction_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(2) > ul > li:nth-child(3)')
    statistic_click_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(2) > ul > li:nth-child(4)')
    statistic_doubles_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(2) > ul > li:nth-child(5)')
    statistic_complaints_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(2) > ul > li:nth-child(6)')
    partner_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(3)')
    source_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(4)')
    streams_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(5)')
    ticket_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(6)')
    landing_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(7)')
    lp_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(7) > ul > li:nth-child(1)')
    top_landing_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(7) > ul > li:nth-child(2)')
    operator_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(7) > ul > li:nth-child(3)')
    category_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(7) > ul > li:nth-child(4)')
    country_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(7) > ul > li:nth-child(5)')
    payments_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(8)')
    orders_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(8) > ul > li:nth-child(1)')
    balance_history_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(8) > ul > li:nth-child(2)')
    individual_commissions_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(8) > ul > li:nth-child(3)')
    news_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(9)')
    rates_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(10)')
    mk_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(11)')
    rates_services_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(11) > ul > li:nth-child(1)')
    modules_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(12)')
    sub_limits_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(12) > ul > li:nth-child(1)')
    general_limits_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(12) > ul > li:nth-child(2)')
    percent_buyout_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(12) > ul > li:nth-child(3)')
    transfer_traf_partner_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(12) > ul > li:nth-child(4)')
    unloading_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(12) > ul > li:nth-child(5)')
    stop_words_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(12) > ul > li:nth-child(6)')
    settings_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(13)')
    common_settings_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(13) > ul > li:nth-child(1)')
    tds_domain_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(13) > ul > li:nth-child(2)')
    tds_partner_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(13) > ul > li:nth-child(3)')
    faq_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(13) > ul > li:nth-child(4)')
    blacklist_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(13) > ul > li:nth-child(5)')
    handlers_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(13) > ul > li:nth-child(6)')
    providers_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(13) > ul > li:nth-child(7)')
    notifications_list_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(13) > ul > li:nth-child(8)')
    partner_group_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(13) > ul > li:nth-child(9)')
    instruments_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(14)')
    event_log_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(14) > ul > li:nth-child(1)')
    system_info_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(14) > ul > li:nth-child(2)')
    database_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(14) > ul > li:nth-child(3)')
    traf_generator_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(14) > ul > li:nth-child(4)')
    providers_errors_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(14) > ul > li:nth-child(5)')
    serious_cash_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(15)')
    lend_list_install_menu = (By.CSS_SELECTOR, '#main-menu > li:nth-child(15) > ul > li:nth-child(1)')


class PartnerLocators:
    partner_button = (By.CSS_SELECTOR, '#main-menu > li:nth-child(3)')
    test_authorization = (By.CSS_SELECTOR, 'div.p-l.p-r.p-t.p-b-0.white.user-panel > ul > li:nth-child(7) > a')
    test_settings = (By.CSS_SELECTOR, '#view > div > div.p-l.p-r.p-t.p-b-0.white.user-panel > ul > li:nth-child(6)')
    test_partner = (By.CSS_SELECTOR, 'tr[data-key="2"] > td[data-col-seq="1"] > div')
    partner_settings = (By.CSS_SELECTOR, '#aside > div > div.hide-scroll > nav > ul > li:nth-child(10)')
    partner_id = (By.CSS_SELECTOR, 'div.col-md-6 > div > div > div:nth-child(1) > small > strong')
    partner_source = (By.CSS_SELECTOR, '#aside > div > div.hide-scroll > nav > ul > li:nth-child(2)')
    partner_tickets = (By.CSS_SELECTOR, '#aside > div > div.hide-scroll > nav > ul > li:nth-child(11)')
    create_source = (By.CSS_SELECTOR, 'button.btn.btn-sm.primary.pull-right')
    type_source_select = (By.CSS_SELECTOR, '#type_id')
    source_name = (By.CSS_SELECTOR, '#name')
    source_url = (By.CSS_SELECTOR, '#url')
    create_source_button = (By.CSS_SELECTOR, 'button.btn.primary.p-x-md')
    partner_alert_button = (By.CSS_SELECTOR, 'div.navbar.ng-scope > ul > li.nav-item.pos-stc-xs > a')
    partner_alert = (By.CSS_SELECTOR, 'ul > li.nav-item.pos-stc-xs > a > span')


class StreamLocators:
    partner_stream = (By.CSS_SELECTOR, '#aside > div > div.hide-scroll > nav > ul > li:nth-child(3)')
    create_stream = (By.CSS_SELECTOR, 'a.btn.btn-sm.primary.pull-right')
    stream_name = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(1) > div > input')
    stream_source = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(2) > div > select')
    traffback_url = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(3) > div > input')
    postback_url = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(4) > div > input')
    postback_check_sub = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(5) > div > label:nth-child(1)')
    postback_check_rebill = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(5) > div > label:nth-child(2)')
    postback_check_unsub = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(5) > div > label:nth-child(3)')
    postback_check_buyout = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(5) > div > label:nth-child(4)')
    redirect_type_simple = (By.CSS_SELECTOR, '[value="redirect"]')
    redirect_type_click_in = (By.CSS_SELECTOR, '[value="clickunder"]')
    redirect_type_click_new = (By.CSS_SELECTOR, '[value="clickunder_newTab"]')
    redirect_type_click_new_inactive = (By.CSS_SELECTOR, '[value="clickunder_newTabInactive"]')
    redirect_type_popup = (By.CSS_SELECTOR, '[value="popup"]')
    redirect_type_push = (By.CSS_SELECTOR, '[value="push"]')
    auto_buyout = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(7) > div > label > input')
    view_land_round = (By.CSS_SELECTOR, 'div:nth-child(8) > div > div:nth-child(1) > label')
    view_land_split = (By.CSS_SELECTOR, 'div:nth-child(8) > div > div:nth-child(2) > label')
    view_land_one_round = (By.CSS_SELECTOR, 'div:nth-child(8) > div > div:nth-child(3) > label')
    ban_ya_redirect = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(9) > div > label > input')
    redirect_limit = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(10) > div > input')
    unic_code_work = (By.CSS_SELECTOR, 'div.col-xl-10 > div:nth-child(11) > div > input')
    landing_mts = (By.CSS_SELECTOR, 'div:nth-child(1) > div.row.m-t-sm > div:nth-child(1) > div > a')
    landing_iplayer = (By.CSS_SELECTOR, 'div:nth-child(3) > label > div.p-a-xs > label > input')
    add_lending_btn = (By.CSS_SELECTOR, 'div.modal-footer.ng-scope > button.btn.primary.p-x-md')
    create_stream_btn = (By.CSS_SELECTOR, 'div.box-footer > button')


class TicketLocators:
    create_button_ticket = (By.CSS_SELECTOR, '#view > div > div > div.box-header > h3 > button')
    ticket_type_select = (By.CSS_SELECTOR, '#type_id')
    ticket_message_type = (By.CSS_SELECTOR, '#topic')
    ticket_message = (By.CSS_SELECTOR, '#message')
    btn_send_ticket = (By.CSS_SELECTOR, 'div.modal-footer > button.btn.primary.p-x-md')
    alert_adm_ticket_icon = (By.CSS_SELECTOR, '#main-menu > li:nth-child(6) > a > i > b')
    adm_send_ticket_btn = (By.CSS_SELECTOR, 'li.nav-item.dropdown.open > div > a:nth-child(4)')
    adm_type_ticket = (By.CSS_SELECTOR, '#supporttickets-type_id:nth-child(2)')
    adm_message_theme = (By.CSS_SELECTOR, '#supporttickets-topic:nth-child(2)')
    adm_message_ticket = (By.CSS_SELECTOR, '#supporttickets-message:nth-child(2)')
    adm_send_message = (By.CSS_SELECTOR, '#supportTicketsForm > div:nth-child(6) > button')
    ticket_header = (By.CSS_SELECTOR, 'div:nth-child(1) > div > div.text-sm.ng-binding > b')


class OperatorLocators:
    operator_create = (By.CSS_SELECTOR, '#view > div > div.m-b > a:nth-child(1)')
    operator_name = (By.CSS_SELECTOR, '#operators-name:nth-child(2)')
    operator_subnet = (By.CSS_SELECTOR, '#operators-subnet:nth-child(2)')
    operator_denied_devices = (By.CSS_SELECTOR, '#operators-deny_devices:nth-child(2)')
    operator_country = (By.CSS_SELECTOR, '#operators-country_id:nth-child(2)')
    operator_on = (By.CSS_SELECTOR, '#operators-status:nth-child(1)')
    operator_web = (By.CSS_SELECTOR, '#operators-is_web:nth-child(1)')
    operator_create_button = (By.CSS_SELECTOR, '#operatorForm > div:nth-child(8) > button')


class CategoryLocators:
    category_add = (By.CSS_SELECTOR, '#view > div > div > div.col-md-6 > div.m-b > a')
    category_name = (By.CSS_SELECTOR, '#categories-name:nth-child(2)')
    category_status = (By.CSS_SELECTOR, '#categories-status:nth-child(1)')
    category_save_button = (By.CSS_SELECTOR, '#categoryForm > div:nth-child(4) > button')


class CountryLocators:
    country_add = (By.CSS_SELECTOR, 'div.btn-toolbar.kv-grid-toolbar.toolbar-container.pull-right > a')
    country_name = (By.CSS_SELECTOR, '#countries-name:nth-child(2)')
    country_iso = (By.CSS_SELECTOR, '#countries-iso:nth-child(2)')
    country_save_button = (By.CSS_SELECTOR, '#countryForm > div:nth-child(4) > button')


class LandingLocators:
    landing_add = (By.CSS_SELECTOR, '#view > div > div.m-b > a:nth-child(1)')
    landing_add_name = (By.CSS_SELECTOR, '#landings-name:nth-child(2)')
    landing_add_web = (By.CSS_SELECTOR, '#landings-is_web:nth-child(1)')
    landing_add_provider = (By.CSS_SELECTOR, '#landings-provider_name:nth-child(2)')
    landing_add_url = (By.CSS_SELECTOR, '#landingForm > div.form-group.provider-params > input')
    landing_add_operator = (By.CSS_SELECTOR, 'span.select2.select2-container.select2-container--krajee.select2'
                                             '-container--below > span.selection > span')
    landing_add_category = (By.CSS_SELECTOR, '#landings-category_id:nth-child(2)')
    landing_add_type = (By.CSS_SELECTOR, '#landings-subscribe_type_id:nth-child(2)')
    landing_add_write_off = (By.CSS_SELECTOR, '#landings-writeoff:nth-child(2)')
    landing_add_static_write_off = (By.CSS_SELECTOR, '#landings-royalties:nth-child(2)')
    landing_add_partner_payments = (By.CSS_SELECTOR, '#landings-partner_deductions:nth-child(2)')
    landing_add_price = (By.CSS_SELECTOR, '#landings-purchase_price:nth-child(2)')
    landing_add_landing_on = (By.CSS_SELECTOR, '#landings-status:nth-child(1)')
    landing_add_save = (By.CSS_SELECTOR, '#landingForm > div:nth-child(29) > button')
    landing_add_static_pays = (By.CSS_SELECTOR, '#landings-static_deductions:nth-child(1)')
